import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialMigration1770934842814 implements MigrationInterface {
    name = 'InitialMigration1770934842814'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "user_follows" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "follower_id" uuid NOT NULL, "following_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_abc657d7ff1282910784b819171" UNIQUE ("follower_id", "following_id"), CONSTRAINT "PK_da8e8793113adf3015952880966" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5a71643cec3110af425f92e76e" ON "user_follows" ("following_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f7af3bf8f2dcba61b4adc10823" ON "user_follows" ("follower_id") `);
        await queryRunner.query(`CREATE TYPE "public"."payment_methods_type_enum" AS ENUM('CARD', 'BANK_ACCOUNT', 'MOBILE_MONEY', 'WALLET', 'BANK_TRANSFER')`);
        await queryRunner.query(`CREATE TABLE "payment_methods" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "type" "public"."payment_methods_type_enum" NOT NULL, "provider" character varying NOT NULL, "token" character varying NOT NULL, "last4" character varying, "brand" character varying, "expiry_month" integer, "expiry_year" integer, "is_default" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_34f9b8c6dfb4ac3559f7e2820d1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d7d7fb15569674aaadcfbc0428" ON "payment_methods" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "add_ons" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "event_id" uuid NOT NULL, "name" character varying, "description" text, "price_cents" integer NOT NULL, "currency" character varying NOT NULL DEFAULT 'USD', "quantity" integer, "quantity_sold" integer NOT NULL DEFAULT '0', "is_visible" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_16b0b20fb9aec455ea78e6065cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_108fb576bcfe7ebcedb68ce56a" ON "add_ons" ("event_id") `);
        await queryRunner.query(`CREATE TABLE "order_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_id" uuid NOT NULL, "ticket_tier_id" uuid, "add_on_id" uuid, "quantity" integer NOT NULL, "unit_price_cents" integer NOT NULL, "total_price_cents" integer NOT NULL, "currency" character varying NOT NULL DEFAULT 'USD', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_005269d8574e6fac0493715c308" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_145532db85752b29c57d2b7b1f" ON "order_items" ("order_id") `);
        await queryRunner.query(`CREATE TYPE "public"."check_ins_method_enum" AS ENUM('QR_SCAN', 'MANUAL', 'KIOSK')`);
        await queryRunner.query(`CREATE TABLE "check_ins" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ticket_id" uuid NOT NULL, "event_id" uuid NOT NULL, "scanner_id" uuid, "method" "public"."check_ins_method_enum" NOT NULL, "device_info" jsonb, "checked_in_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fac7f27bc829a454ad477c13f62" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_aa021e08eca9624b17bc501000" ON "check_ins" ("event_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_faf95a47d1dc8359442af40b77" ON "check_ins" ("ticket_id") `);
        await queryRunner.query(`CREATE TYPE "public"."tickets_status_enum" AS ENUM('ACTIVE', 'USED', 'REFUNDED', 'CANCELLED', 'EXPIRED')`);
        await queryRunner.query(`CREATE TABLE "tickets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ticket_id" character varying NOT NULL, "order_id" uuid NOT NULL, "event_id" uuid NOT NULL, "ticket_tier_id" uuid NOT NULL, "owner_id" uuid NOT NULL, "issued_to_name" character varying NOT NULL, "issued_to_email" character varying NOT NULL, "seat_number" character varying NOT NULL, "seat_zone" character varying, "qr_code_data" character varying NOT NULL, "qr_code_image_url" character varying NOT NULL, "status" "public"."tickets_status_enum" NOT NULL DEFAULT 'ACTIVE', "issued_at" TIMESTAMP NOT NULL DEFAULT now(), "expires_at" TIMESTAMP, "used_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8de0cebd669ff84059e9976e17d" UNIQUE ("ticket_id"), CONSTRAINT "PK_343bc942ae261cf7a1377f48fd0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_12b901b34113688b4786368510" ON "tickets" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_5051ef7bf7d664ad1d081a110e" ON "tickets" ("owner_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bd5387c23fb40ae7e3526ad75e" ON "tickets" ("event_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bd5636236f799b19f132abf8d7" ON "tickets" ("order_id") `);
        await queryRunner.query(`CREATE TABLE "ticket_tiers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "event_id" uuid NOT NULL, "name" character varying NOT NULL, "description" text, "price_cents" integer NOT NULL, "currency" character varying NOT NULL DEFAULT 'NGN', "quantity" integer NOT NULL, "quantity_sold" integer NOT NULL DEFAULT '0', "sales_start" TIMESTAMP NOT NULL, "sales_end" TIMESTAMP NOT NULL, "is_refundable" boolean NOT NULL DEFAULT true, "refundable_until" TIMESTAMP, "features" text, "has_reserved_seating" boolean NOT NULL DEFAULT false, "seat_zone" character varying, "is_visible" boolean NOT NULL DEFAULT true, "sort_order" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_917cfec124fa5e8ce04d1e7b865" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_73e479ba60b35caae8249e94c8" ON "ticket_tiers" ("event_id") `);
        await queryRunner.query(`CREATE TYPE "public"."promo_codes_discount_type_enum" AS ENUM('PERCENTAGE', 'FIXED_AMOUNT')`);
        await queryRunner.query(`CREATE TABLE "promo_codes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "event_id" uuid NOT NULL, "code" character varying NOT NULL, "discount_type" "public"."promo_codes_discount_type_enum" NOT NULL, "discount_value" numeric(10,2) NOT NULL, "usage_limit" integer, "usage_count" integer NOT NULL DEFAULT '0', "valid_from" TIMESTAMP NOT NULL, "valid_until" TIMESTAMP NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_779d73e7d9aede29a4399084588" UNIQUE ("event_id", "code"), CONSTRAINT "PK_c7b4f01710fda5afa056a2b4a35" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2f096c406a9d9d5b8ce204190c" ON "promo_codes" ("code") `);
        await queryRunner.query(`CREATE TABLE "reviews" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "event_id" uuid NOT NULL, "rating" integer NOT NULL, "title" character varying, "comment" text, "is_verified_attendee" boolean NOT NULL DEFAULT false, "helpful_count" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_48d2c877eecd9ec629a6d668556" UNIQUE ("user_id", "event_id"), CONSTRAINT "PK_231ae565c273ee700b283f15c1d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f4b88c05a7adf404a6e6b2f1eb" ON "reviews" ("rating") `);
        await queryRunner.query(`CREATE INDEX "IDX_aa7772d94b254e2fc02d672493" ON "reviews" ("event_id") `);
        await queryRunner.query(`CREATE TYPE "public"."user_interactions_interaction_type_enum" AS ENUM('VIEW', 'CLICK', 'SHARE', 'FAVORITE', 'SEARCH')`);
        await queryRunner.query(`CREATE TABLE "user_interactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "event_id" uuid NOT NULL, "interaction_type" "public"."user_interactions_interaction_type_enum" NOT NULL, "session_id" character varying, "source" character varying, "device_type" character varying, "duration_seconds" integer, "scroll_depth" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_173313ad3f40a2ae74b48f82dd7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c6efbf27f088ae2a07ce52218c" ON "user_interactions" ("event_id", "interaction_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_607386da74b4f2046272c9fc9c" ON "user_interactions" ("user_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "favorites" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "event_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_a988b004ac89d43755511fdf88f" UNIQUE ("user_id", "event_id"), CONSTRAINT "PK_890818d27523748dd36a4d1bdc8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_35a6b05ee3b624d0de01ee5059" ON "favorites" ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."events_status_enum" AS ENUM('DRAFT', 'PUBLISHED', 'CANCELLED', 'COMPLETED')`);
        await queryRunner.query(`CREATE TYPE "public"."events_accesstype_enum" AS ENUM('PUBLIC', 'INVITE_ONLY', 'PRIVATE')`);
        await queryRunner.query(`CREATE TABLE "events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "slug" character varying NOT NULL, "description" text, "coverImages" text, "startDateTime" TIMESTAMP NOT NULL, "endDateTime" TIMESTAMP NOT NULL, "venueName" character varying, "venueAddress" character varying, "city" character varying, "state" character varying, "country" character varying, "isOnline" boolean NOT NULL DEFAULT false, "streamingUrl" character varying, "status" "public"."events_status_enum" NOT NULL DEFAULT 'DRAFT', "accessType" "public"."events_accesstype_enum" NOT NULL DEFAULT 'PUBLIC', "timezone" character varying, "category" character varying, "refundableUntil" TIMESTAMP, "host_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_05bd884c03d3f424e2204bd14cd" UNIQUE ("slug"), CONSTRAINT "PK_40731c7151fe4be3116e45ddf73" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."refunds_status_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED', 'COMPLETED')`);
        await queryRunner.query(`CREATE TABLE "refunds" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_id" uuid NOT NULL, "amount_cents" integer NOT NULL, "currency" character varying NOT NULL DEFAULT 'USD', "reason" text, "status" "public"."refunds_status_enum" NOT NULL DEFAULT 'PENDING', "refund_id" character varying, "requested_at" TIMESTAMP NOT NULL DEFAULT now(), "processed_at" TIMESTAMP, CONSTRAINT "PK_5106efb01eeda7e49a78b869738" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a42db6369017df60549539f556" ON "refunds" ("order_id") `);
        await queryRunner.query(`CREATE TYPE "public"."orders_status_enum" AS ENUM('PENDING', 'PROCESSING', 'CONFIRMED', 'FAILED', 'REFUNDED', 'PARTIALLY_REFUNDED')`);
        await queryRunner.query(`CREATE TYPE "public"."orders_payment_status_enum" AS ENUM('PENDING', 'PROCESSING', 'SUCCEEDED', 'FAILED', 'REFUNDED', 'PARTIALLY_REFUNDED')`);
        await queryRunner.query(`CREATE TABLE "orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_reference" character varying NOT NULL, "user_id" uuid NOT NULL, "event_id" uuid NOT NULL, "status" "public"."orders_status_enum" NOT NULL DEFAULT 'PENDING', "subtotal_cents" integer NOT NULL, "platform_fee_cents" integer NOT NULL, "host_fee_cents" integer NOT NULL DEFAULT '0', "tax_cents" integer NOT NULL DEFAULT '0', "discount_cents" integer NOT NULL DEFAULT '0', "total_cents" integer NOT NULL, "currency" character varying NOT NULL DEFAULT 'USD', "promo_code_id" uuid, "attendee_info" jsonb, "payment_provider" character varying, "payment_intent_id" character varying, "payment_status" "public"."orders_payment_status_enum" NOT NULL DEFAULT 'PENDING', "paid_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_163a3c044a17987219c85b16fb9" UNIQUE ("order_reference"), CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c884e321f927d5b86aac7c8f9e" ON "orders" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_775c9f06fc27ae3ff8fb26f2c4" ON "orders" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_642ca308ac51fea8327e593b8a" ON "orders" ("event_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a922b820eeef29ac1c6800e826" ON "orders" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "search_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "query" character varying NOT NULL, "filters" jsonb, "results_count" integer NOT NULL, "clicked_event_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_cb93c8f85dbdca85943ca494812" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c3e3193c5bd8073f56bdd62673" ON "search_history" ("user_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "type" character varying NOT NULL, "title" character varying NOT NULL, "message" text NOT NULL, "data" jsonb, "is_read" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_af08fad7c04bb85403970afdc1" ON "notifications" ("user_id", "is_read") `);
        await queryRunner.query(`CREATE TYPE "public"."payouts_status_enum" AS ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "payouts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "host_id" uuid NOT NULL, "amount_cents" integer NOT NULL, "currency" character varying NOT NULL DEFAULT 'USD', "provider" character varying NOT NULL, "payout_id" character varying, "status" "public"."payouts_status_enum" NOT NULL DEFAULT 'PENDING', "period_start" TIMESTAMP NOT NULL, "period_end" TIMESTAMP NOT NULL, "order_count" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "processed_at" TIMESTAMP, CONSTRAINT "PK_76855dc4f0a6c18c72eea302e87" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3f32ee6d2385d9a8bc0cc92af5" ON "payouts" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_546fa9f0f39336406ad8a95209" ON "payouts" ("host_id") `);
        await queryRunner.query(`CREATE TABLE "customer_support" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "subject" character varying, "message" text, "category" character varying, "status" character varying NOT NULL DEFAULT 'OPEN', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_cc864d06accbb228be3826432be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('HOST', 'ATTENDEE')`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED', 'BANNED')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "firstName" character varying, "lastName" character varying, "email" character varying NOT NULL, "password" character varying, "phoneNumber" character varying, "role" "public"."users_role_enum" NOT NULL DEFAULT 'ATTENDEE', "status" "public"."users_status_enum" NOT NULL DEFAULT 'ACTIVE', "googleId" character varying, "facebookId" character varying, "emailVerified" boolean NOT NULL DEFAULT false, "profilePictureUrl" character varying, "organizationName" character varying, "contactEmail" character varying, "contactPhone" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_event_scores" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" character varying NOT NULL, "event_id" character varying NOT NULL, "score" double precision NOT NULL, "collaborative_score" double precision, "content_score" double precision, "popularity_score" double precision, "recency_score" double precision, "computed_at" TIMESTAMP NOT NULL, CONSTRAINT "UQ_55366192c1a89974c718472a6f1" UNIQUE ("user_id", "event_id"), CONSTRAINT "PK_3085352d1281008b594a6ef938f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c3205e0b1cc4f554943cc3530e" ON "user_event_scores" ("computed_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_ec6c27ef4d61d0a1d2d8fa282e" ON "user_event_scores" ("user_id", "score") `);
        await queryRunner.query(`ALTER TABLE "user_follows" ADD CONSTRAINT "FK_f7af3bf8f2dcba61b4adc108239" FOREIGN KEY ("follower_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_follows" ADD CONSTRAINT "FK_5a71643cec3110af425f92e76e5" FOREIGN KEY ("following_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_methods" ADD CONSTRAINT "FK_d7d7fb15569674aaadcfbc0428c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "add_ons" ADD CONSTRAINT "FK_108fb576bcfe7ebcedb68ce56aa" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_145532db85752b29c57d2b7b1f1" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_6916eb7860e5de23fde64198155" FOREIGN KEY ("ticket_tier_id") REFERENCES "ticket_tiers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_f148f8e8e8a968a1d511e81077d" FOREIGN KEY ("add_on_id") REFERENCES "add_ons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "check_ins" ADD CONSTRAINT "FK_faf95a47d1dc8359442af40b772" FOREIGN KEY ("ticket_id") REFERENCES "tickets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "check_ins" ADD CONSTRAINT "FK_aa021e08eca9624b17bc501000a" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "check_ins" ADD CONSTRAINT "FK_1dda036265fd84fe34683d58c97" FOREIGN KEY ("scanner_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_bd5636236f799b19f132abf8d70" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_bd5387c23fb40ae7e3526ad75ea" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_f47b1a43db19416cdba835f7904" FOREIGN KEY ("ticket_tier_id") REFERENCES "ticket_tiers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_5051ef7bf7d664ad1d081a110e6" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ticket_tiers" ADD CONSTRAINT "FK_73e479ba60b35caae8249e94c81" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "promo_codes" ADD CONSTRAINT "FK_1ebec1c7d9c344f85c9af5313e8" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_728447781a30bc3fcfe5c2f1cdf" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_aa7772d94b254e2fc02d6724935" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_interactions" ADD CONSTRAINT "FK_8165cbaf68d8c40e80bda6468a7" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_interactions" ADD CONSTRAINT "FK_b2ab5b633b1431a72d3c83bfcfa" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD CONSTRAINT "FK_35a6b05ee3b624d0de01ee50593" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD CONSTRAINT "FK_b4bd4b6a0d2dca5cfa98905bb81" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events" ADD CONSTRAINT "FK_a612b523901cc5dd938ff3bdb03" FOREIGN KEY ("host_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refunds" ADD CONSTRAINT "FK_a42db6369017df60549539f5567" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_a922b820eeef29ac1c6800e826a" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_642ca308ac51fea8327e593b8ab" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_1e7814b20d15af2aa03320e0451" FOREIGN KEY ("promo_code_id") REFERENCES "promo_codes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "search_history" ADD CONSTRAINT "FK_d1ebf4101b2804213251e0a04d2" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payouts" ADD CONSTRAINT "FK_546fa9f0f39336406ad8a95209d" FOREIGN KEY ("host_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_support" ADD CONSTRAINT "FK_7201620fb546b2bc6aaf499b783" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "customer_support" DROP CONSTRAINT "FK_7201620fb546b2bc6aaf499b783"`);
        await queryRunner.query(`ALTER TABLE "payouts" DROP CONSTRAINT "FK_546fa9f0f39336406ad8a95209d"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "search_history" DROP CONSTRAINT "FK_d1ebf4101b2804213251e0a04d2"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_1e7814b20d15af2aa03320e0451"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_642ca308ac51fea8327e593b8ab"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_a922b820eeef29ac1c6800e826a"`);
        await queryRunner.query(`ALTER TABLE "refunds" DROP CONSTRAINT "FK_a42db6369017df60549539f5567"`);
        await queryRunner.query(`ALTER TABLE "events" DROP CONSTRAINT "FK_a612b523901cc5dd938ff3bdb03"`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP CONSTRAINT "FK_b4bd4b6a0d2dca5cfa98905bb81"`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP CONSTRAINT "FK_35a6b05ee3b624d0de01ee50593"`);
        await queryRunner.query(`ALTER TABLE "user_interactions" DROP CONSTRAINT "FK_b2ab5b633b1431a72d3c83bfcfa"`);
        await queryRunner.query(`ALTER TABLE "user_interactions" DROP CONSTRAINT "FK_8165cbaf68d8c40e80bda6468a7"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_aa7772d94b254e2fc02d6724935"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_728447781a30bc3fcfe5c2f1cdf"`);
        await queryRunner.query(`ALTER TABLE "promo_codes" DROP CONSTRAINT "FK_1ebec1c7d9c344f85c9af5313e8"`);
        await queryRunner.query(`ALTER TABLE "ticket_tiers" DROP CONSTRAINT "FK_73e479ba60b35caae8249e94c81"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_5051ef7bf7d664ad1d081a110e6"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_f47b1a43db19416cdba835f7904"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_bd5387c23fb40ae7e3526ad75ea"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_bd5636236f799b19f132abf8d70"`);
        await queryRunner.query(`ALTER TABLE "check_ins" DROP CONSTRAINT "FK_1dda036265fd84fe34683d58c97"`);
        await queryRunner.query(`ALTER TABLE "check_ins" DROP CONSTRAINT "FK_aa021e08eca9624b17bc501000a"`);
        await queryRunner.query(`ALTER TABLE "check_ins" DROP CONSTRAINT "FK_faf95a47d1dc8359442af40b772"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_f148f8e8e8a968a1d511e81077d"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_6916eb7860e5de23fde64198155"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_145532db85752b29c57d2b7b1f1"`);
        await queryRunner.query(`ALTER TABLE "add_ons" DROP CONSTRAINT "FK_108fb576bcfe7ebcedb68ce56aa"`);
        await queryRunner.query(`ALTER TABLE "payment_methods" DROP CONSTRAINT "FK_d7d7fb15569674aaadcfbc0428c"`);
        await queryRunner.query(`ALTER TABLE "user_follows" DROP CONSTRAINT "FK_5a71643cec3110af425f92e76e5"`);
        await queryRunner.query(`ALTER TABLE "user_follows" DROP CONSTRAINT "FK_f7af3bf8f2dcba61b4adc108239"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ec6c27ef4d61d0a1d2d8fa282e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c3205e0b1cc4f554943cc3530e"`);
        await queryRunner.query(`DROP TABLE "user_event_scores"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP TABLE "customer_support"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_546fa9f0f39336406ad8a95209"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3f32ee6d2385d9a8bc0cc92af5"`);
        await queryRunner.query(`DROP TABLE "payouts"`);
        await queryRunner.query(`DROP TYPE "public"."payouts_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_af08fad7c04bb85403970afdc1"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c3e3193c5bd8073f56bdd62673"`);
        await queryRunner.query(`DROP TABLE "search_history"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a922b820eeef29ac1c6800e826"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_642ca308ac51fea8327e593b8a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_775c9f06fc27ae3ff8fb26f2c4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c884e321f927d5b86aac7c8f9e"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP TYPE "public"."orders_payment_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."orders_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a42db6369017df60549539f556"`);
        await queryRunner.query(`DROP TABLE "refunds"`);
        await queryRunner.query(`DROP TYPE "public"."refunds_status_enum"`);
        await queryRunner.query(`DROP TABLE "events"`);
        await queryRunner.query(`DROP TYPE "public"."events_accesstype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."events_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_35a6b05ee3b624d0de01ee5059"`);
        await queryRunner.query(`DROP TABLE "favorites"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_607386da74b4f2046272c9fc9c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c6efbf27f088ae2a07ce52218c"`);
        await queryRunner.query(`DROP TABLE "user_interactions"`);
        await queryRunner.query(`DROP TYPE "public"."user_interactions_interaction_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aa7772d94b254e2fc02d672493"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f4b88c05a7adf404a6e6b2f1eb"`);
        await queryRunner.query(`DROP TABLE "reviews"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2f096c406a9d9d5b8ce204190c"`);
        await queryRunner.query(`DROP TABLE "promo_codes"`);
        await queryRunner.query(`DROP TYPE "public"."promo_codes_discount_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_73e479ba60b35caae8249e94c8"`);
        await queryRunner.query(`DROP TABLE "ticket_tiers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bd5636236f799b19f132abf8d7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bd5387c23fb40ae7e3526ad75e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5051ef7bf7d664ad1d081a110e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_12b901b34113688b4786368510"`);
        await queryRunner.query(`DROP TABLE "tickets"`);
        await queryRunner.query(`DROP TYPE "public"."tickets_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_faf95a47d1dc8359442af40b77"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aa021e08eca9624b17bc501000"`);
        await queryRunner.query(`DROP TABLE "check_ins"`);
        await queryRunner.query(`DROP TYPE "public"."check_ins_method_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_145532db85752b29c57d2b7b1f"`);
        await queryRunner.query(`DROP TABLE "order_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_108fb576bcfe7ebcedb68ce56a"`);
        await queryRunner.query(`DROP TABLE "add_ons"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d7d7fb15569674aaadcfbc0428"`);
        await queryRunner.query(`DROP TABLE "payment_methods"`);
        await queryRunner.query(`DROP TYPE "public"."payment_methods_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f7af3bf8f2dcba61b4adc10823"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5a71643cec3110af425f92e76e"`);
        await queryRunner.query(`DROP TABLE "user_follows"`);
    }

}
